[phases.setup]
nixPkgs = ['php84', 'php84Packages.composer', 'php84Extensions.pdo', 'php84Extensions.pdo_pgsql', 'php84Extensions.mbstring', 'php84Extensions.xml', 'php84Extensions.curl', 'php84Extensions.zip', 'php84Extensions.gd', 'php84Extensions.intl', 'php84Extensions.bcmath']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist']

[phases.build]
cmds = [
    'php artisan view:cache'
]

[start]
cmd = 'echo "DATABASE_URL=$DATABASE_URL" && echo "DB_HOST=$DB_HOST" && php artisan config:clear && php artisan cache:clear && php artisan route:clear && php artisan view:clear && php artisan migrate --force && php artisan admin:create && php artisan serve --host=0.0.0.0 --port=$PORT'
