[phases.setup]
nixPkgs = ['php84', 'php84Packages.composer', 'php84Extensions.pdo', 'php84Extensions.pdo_pgsql', 'php84Extensions.mbstring', 'php84Extensions.xml', 'php84Extensions.curl', 'php84Extensions.zip', 'php84Extensions.gd', 'php84Extensions.intl', 'php84Extensions.bcmath']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist']

[phases.build]
cmds = [
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan admin:create && php artisan config:clear && php artisan serve --host=0.0.0.0 --port=$PORT'
