[phases.setup]
nixPkgs = [
    'php83Packages.php',
    'php83Packages.composer',

    'php83Extensions.iconv',
    'php83Extensions.mbstring',
    'php83Extensions.pdo',
    'php83Extensions.pdo_pgsql',
    'php83Extensions.pgsql',
    'php83Extensions.xml',
    'php83Extensions.curl',
    'php83Extensions.zip',
    'php83Extensions.gd',
    'php83Extensions.intl',
    'php83Extensions.bcmath',
    'php83Extensions.exif',
    'php83Extensions.ctype',
    'php83Extensions.dom',
    'php83Extensions.fileinfo',
    'php83Extensions.filter',
    'php83Extensions.openssl',
    'php83Extensions.session',
    'php83Extensions.tokenizer'
]

cmds = [
    'php -v',
    'php -m | grep pgsql',
    'php -r "print_r(PDO::getAvailableDrivers());"'
]

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-interaction --prefer-dist'
]

[phases.build]
cmds = [
    'php artisan config:clear',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
